"use client"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/common/Header";
// import MainContext from "./context/MainContext";
import { Provider, useSelector } from "react-redux";
import { store } from "./redux/store";
import AdminLayout, { HomePage } from "./AdminLayout";
import "primereact/resources/themes/lara-light-indigo/theme.css";
import "primereact/resources/primereact.min.css";
import Footer from "@/common/Footer";
import Login from "./auth/login/page";
import { useEffect, useState } from "react";
import LoginBasedLayout from "./LoginBasedLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  // return (
  //   <html>
  //     <body>
  //       <div>"Hello i am layout.js</div>
  //       {children}
  //     </body>
  //   </html>
  // );
      let [showHomePage, setShowHomePage] = useState(true);
          // const user = useSelector((state) => state.user.token);
          // const user = JSON.parse(localStorage.getItem('jwt-token'));
          
          // if(typeof window !== "undefined"){
          //      const user = JSON.parse(localStorage.getItem("jwt-token"));
          // }

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Provider store={store}>
            <Header/>
              <LoginBasedLayout>
            {children}
            </LoginBasedLayout>
            <Footer/>
        </Provider>
      </body>
    </html>
  );
}
